backend:
  name: git-gateway
  branch: main  # замени на master, если у тебя так называется ветка

media_folder: "static/images/uploads"   # папка для загрузки медиа в репозитории
public_folder: "/images/uploads"        # путь для доступа к этим файлам на сайте

media_library:
  name: uploadcare

collections:
  - name: news
    label: Новости
    folder: news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Заголовок, name: title, widget: string }
      - { label: Дата, name: date, widget: datetime }
      - { label: Текст, name: body, widget: markdown }
